export const TABLE_NAME = Symbol("TABLE_NAME")
export const TABLE_ALIAS = Symbol("TABLE_ALIAS")
export const COLUMNS = Symbol("COLUMNS")
export const MULTIPLE_TABLES = Symbol("MULTIPLE_TABLES")
export const TYPE = Symbol("TYPE")
export const PHANTOM_INSTANCE = Symbol("PHANTOM_INSTANCE")
export const COLUMN_DEFINITION = Symbol("COLUMN_DEFINITION")
export const RAW_SQL = Symbol("RAW_SQL")
