export const TABLE_NAME = Symbol()
export const TABLE_ALIAS = Symbol()
export const COLUMNS = Symbol()
export const MULTIPLE_TABLES = Symbol()
export const TYPE = Symbol()
export const PHANTOM_INSTANCE = Symbol()
export const COLUMN_DEFINITION = Symbol()
export const RAW_SQL = Symbol()
