on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.2
              with:
                  token: ${{secrets.ROBEADY_GITHUB_PAT}}
                  submodules: recursive
            - uses: actions/setup-node@v1
              with:
                  node-version: "14"
            - run: yarn install --frozen-lockfile
            - run: yarn run compile
            - run: yarn test
            - run: yarn run lint:check
            - run: yarn run format:check
            - if: github.ref == 'refs/heads/master'
              env:
                  USER: ${{secrets.DEPLOY_USER}}
                  TOKEN: ${{secrets.DEPLOY_TOKEN}}
                  HOST: ${{secrets.DEPLOY_HOST}}
              run: scripts/deploy.sh
