name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
      with:
        token: ${{secrets.ROBEADY_GITHUB_PAT}}
        submodules: recursive 
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: yarn --cwd app install --frozen-lockfile
    - run: yarn --cwd app test
